name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cinephoria-backend

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lancer les tests backend
        run: |
          source .venv/bin/activate
          pytest -q
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps & run tests
        run: |
          # on rentre dans le dossier qui contient app/ et tests/
          cd cinephoria-backend

          # création du venv
          python -m venv .venv
          source .venv/bin/activate

          # installation des requirements
          pip install --upgrade pip
          pip install -r requirements.txt

          # exécution des tests
          pytest -q
